import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { SEOSection } from '../../../types';
import type { FpvDroneSpeedLocaleContent } from '../entry';
import { BIBLIOGRAPHY_ITEMS } from '../bibliography';

const title = 'Geschwindigkeitsrechner für FPV Drohnen';
const description = 'Schätze die Vorwärtsgeschwindigkeit aus Motor KV, Akkuspannung, Propellersteigung, Wirkungsgrad und Flugmasse und sieh Schlupf und Empfindlichkeit getrennt.';
const ui = { presetsLabel: 'Mit einem Flugsetup starten', presetRacing: 'Racing 4S', presetFreestyle: 'Freestyle 6S', presetCruiser: 'Cruiser 7 Zoll', unitsLabel: 'Anzeigeeinheiten', metricUnit: 'Metrisch', imperialUnit: 'Imperial', inputsLabel: 'Flugrezept', motorKvLabel: 'Motor KV', batteryVoltageLabel: 'Akkuspannung', propellerPitchLabel: 'Propellersteigung', efficiencyLabel: 'Wirkungsgradschätzung', aircraftMassLabel: 'Flugmasse', calculateFromLabel: 'Schätzung aus fünf Eingaben', resultsLabel: 'Flugspur', estimatedSpeedLabel: 'Geschätzte Vorwärtsgeschwindigkeit', pitchSpeedLabel: 'Steiggeschwindigkeit ohne Schlupf', loadedRpmLabel: 'Motordrehzahl unter Last', noLoadRpmLabel: 'Drehzahl ohne Last', slipLabel: 'Durch Schlupf verlorene Geschwindigkeit', loadEffectLabel: 'Lastkorrektur', speedLaneLabel: 'Geschwindigkeitsspur des Propellers', sensitivityLabel: 'Nur eine Änderung auf einmal', lowerPitchLabel: 'Kleinere Steigung', selectedPitchLabel: 'Gewählte Steigung', higherPitchLabel: 'Größere Steigung', diagnosisLabel: 'Einordnung', diagnosisPlanning: 'Planungsschätzung', diagnosisHighSlip: 'Hoher Schlupf', diagnosisHeavyLoad: 'Hohe Last', diagnosisOverspeed: 'Drehzahl prüfen', diagnosisPlanningAdvice: 'Nutze dies als erste Größenordnung und vergleiche sie danach mit Herstellerdaten oder einem Prüfstand.', diagnosisHighSlipAdvice: 'Der gewählte Wirkungsgrad lässt eine große Lücke zwischen geometrischer Steiggeschwindigkeit und Vorwärtsflug. Prüfe Last, Spannungseinbruch und Motortemperatur.', diagnosisHeavyLoadAdvice: 'Die Flugmasse macht die Lastkorrektur wichtiger. Behandle die Geschwindigkeit als groben Planungsbereich und prüfe den kompletten Antrieb.', diagnosisOverspeedAdvice: 'Die Leerlaufdrehzahl ist für dieses Setup ungewöhnlich hoch. Prüfe Motor, Akku und Propellergrenzen vor dem Einschalten.', assumptionsLabel: 'Modellgrenze.', assumptionsText: 'Die Steiggeschwindigkeit ist geometrisch: Steigung mal belastete Drehzahl. Der Wirkungsgrad ist ein eingegebener Näherungswert für Schlupf; die Masse erzeugt eine kleine, sichtbare Lastkorrektur. Propellerdurchmesser, Schubkurve und Wind fehlen.', safetyText: 'Keine Fluggarantie. Halte Abstand zum Propeller und prüfe Strom, Temperatur, Vibrationen und Geschwindigkeit kontrolliert.', speedAxisStart: '0 km/h', speedAxisEnd: '300 km/h', noLoadCaption: 'ohne Last', loadedCaption: 'belastet', slipCaption: 'Schlupf', massUnit: 'g', speedUnit: 'km/h' } satisfies Record<string, string>;
const faq = [
  { question: 'Wie wird die Steiggeschwindigkeit einer FPV Drohne berechnet?', answer: 'Die Propellersteigung wird mit der belasteten Drehzahl multipliziert und von Zoll pro Umdrehung in Kilometer pro Stunde umgerechnet. Das ist eine geometrische Geschwindigkeit ohne Schlupf und keine Zusage für die Fluggeschwindigkeit.' },
  { question: 'Was bedeutet Wirkungsgrad in dieser Schätzung?', answer: 'Der Wirkungsgrad ist ein Planungswert für die Lücke zwischen geometrischer Steiggeschwindigkeit und geschätztem Vortrieb. Er ersetzt keine Propellerkennlinie und keinen Flugtest.' },
  { question: 'Warum beeinflusst die Flugmasse das Ergebnis?', answer: 'Ein schweres Fluggerät belastet den Antrieb meist stärker. Das Modell verwendet deshalb eine kleine begrenzte Drehzahlkorrektur. Ohne Durchmesser, Schubdaten und Motordrehmoment bleibt sie eine transparente Näherung.' },
  { question: 'Bestätigt der Rechner, dass die Drohne sicher fliegt?', answer: 'Nein. Motor, ESC, Akku, Propeller, Rahmen und Flugsteuerung müssen anhand ihrer Herstellergrenzen und eines gesicherten Prüfstands geprüft werden.' },
  { question: 'Warum ist die echte Geschwindigkeit kleiner als die Steigungsgeschwindigkeit?', answer: 'Die geometrische Geschwindigkeit nimmt an, dass der Propeller seine Nennsteigung pro Umdrehung vorrückt. Schlupf, Blattform, Spannungseinbruch, Last und Einbauverluste verringern den nutzbaren Vortrieb.' },
];
const howTo = [{ name: 'Antrieb eingeben', text: 'Gib Motor KV und die erwartete Akkuspannung unter Last ein, nicht nur den Nennwert des Akkus.' }, { name: 'Propeller und Fluggerät beschreiben', text: 'Gib Steigung, einen vorsichtigen Wirkungsgrad und die flugfertige Masse ein. Ein Preset hilft beim Start.' }, { name: 'Spur lesen und prüfen', text: 'Vergleiche Schätzung, Steiggeschwindigkeit, Schlupf und Steigungsempfindlichkeit. Verwende das Ergebnis als Prüfplan.' }];
const seo: SEOSection[] = [{ type: 'title', text: 'FPV Drohnengeschwindigkeit aus der Propellersteigung schätzen', level: 2 }, { type: 'paragraph', html: 'Eine Geschwindigkeitsschätzung für FPV Drohnen beginnt mit der Strecke, die ein Propeller mit fester Steigung pro Umdrehung zurücklegen würde. Motor KV und Akkuspannung liefern eine erste Drehzahl; Wirkungsgrad und Flugmasse setzen die Zahl in einen vorsichtigen Planungsrahmen. Der Rechner zeigt geometrische Steiggeschwindigkeit und geschätzten Vortrieb gemeinsam, damit Annahmen nicht mit Messwerten verwechselt werden.' }, { type: 'title', text: 'Die Geschwindigkeitsspur lesen', level: 2 }, { type: 'table', headers: ['Signal', 'Bedeutung'], rows: [['Steigung ohne Schlupf', 'Steigung mal belastete Drehzahl; jede Umdrehung bewegt den Propeller um seine Nennsteigung.'], ['Geschätzter Vortrieb', 'Der Wert ohne Schlupf, multipliziert mit dem eingegebenen Wirkungsgrad.'], ['Verlorene Geschwindigkeit', 'Prozentuale Lücke zwischen geometrischer Steigung und geschätztem Vortrieb.'], ['Steigungsempfindlichkeit', 'Ergebnis bei 0,5 Zoll weniger oder mehr Steigung im gleichen Setup.']] }, { type: 'title', text: 'Die Schätzung sinnvoll verwenden', level: 2 }, { type: 'list', items: ['Verwende die erwartete Spannung unter Last.', 'Beginne mit bekannten Motor Propeller Daten oder Herstellerwerten.', 'Nutze hohen Schlupf als Hinweis, Last, Spannungseinbruch und Propellerwahl zu prüfen.', 'Kontrolliere Strom, Temperatur, Vibrationen und echte Geschwindigkeit vor dem Flug.'] }, { type: 'paragraph', html: 'Propellerleistung verändert sich mit Fortschrittsgrad, Blattgeometrie, Luftdichte, Zufluss und Betriebswinkel. Forschungsmethoden für UAV Propeller verwenden gemessene oder identifizierte Aerodynamikdaten. Dieser Rechner bleibt bewusst einfacher und ersetzt weder Kennlinie noch Schubprüfstand.' }, { type: 'tip', title: 'Die Lücke als Entscheidungshilfe nutzen', html: 'Wenn ein Setup nur wegen einer hohen Zahl ohne Schlupf schnell wirkt, prüfe die Differenz zur wirkungsgradbereinigten Schätzung. Eine kleinere Steigung kann die Last verringern, braucht aber weiterhin eine echte Antriebsprüfung.' }];
const schemas: FpvDroneSpeedLocaleContent['schemas'] = [{ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) } as WithContext<FAQPage>, { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) } as WithContext<HowTo>, { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' } } as WithContext<SoftwareApplication>];
export const content: FpvDroneSpeedLocaleContent = { slug: 'fpv-drohnen-geschwindigkeitsrechner', title, description, ui, seo, faq, bibliography: BIBLIOGRAPHY_ITEMS, howTo, schemas };
seo.push({ type: 'title', text: 'Messung bleibt der letzte Schritt', level: 2 });
