import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { SEOSection } from '../../../types';
import type { FpvDroneSpeedLocaleContent } from '../entry';
import { BIBLIOGRAPHY_ITEMS } from '../bibliography';

const slug = 'calculadora-velocidad-drone-fpv';
const title = 'Calculadora de Velocidad para Drones FPV';
const description = 'Estima la velocidad de un dron FPV a partir del KV del motor, el voltaje, el paso de hélice, la eficiencia y la masa de la aeronave, mostrando el deslizamiento y la sensibilidad.';
const ui = {
  presetsLabel: 'Empieza con un montaje', presetRacing: 'Carreras 4S', presetFreestyle: 'Freestyle 6S', presetCruiser: 'Crucero 7 pulgadas', unitsLabel: 'Unidades de pantalla', metricUnit: 'Métrico', imperialUnit: 'Imperial', inputsLabel: 'Receta de vuelo', motorKvLabel: 'KV del motor', batteryVoltageLabel: 'Voltaje de batería', propellerPitchLabel: 'Paso de hélice', efficiencyLabel: 'Estimación de eficiencia', aircraftMassLabel: 'Masa de la aeronave', calculateFromLabel: 'Construye la estimación con cinco datos', resultsLabel: 'Trazado de vuelo', estimatedSpeedLabel: 'Velocidad de avance estimada', pitchSpeedLabel: 'Velocidad de paso sin deslizamiento', loadedRpmLabel: 'Velocidad cargada del motor', noLoadRpmLabel: 'RPM sin carga', slipLabel: 'Velocidad perdida por deslizamiento', loadEffectLabel: 'Corrección por carga', speedLaneLabel: 'Carril de velocidad de la hélice', sensitivityLabel: 'Cambia una cosa cada vez', lowerPitchLabel: 'Paso menor', selectedPitchLabel: 'Paso elegido', higherPitchLabel: 'Paso mayor', diagnosisLabel: 'Lectura', diagnosisPlanning: 'Estimación de planificación', diagnosisHighSlip: 'Deslizamiento alto', diagnosisHeavyLoad: 'Carga alta', diagnosisOverspeed: 'Revisa las RPM', diagnosisPlanningAdvice: 'Úsalo como primera comparación y contrástalo con una tabla del fabricante o un ensayo en banco.', diagnosisHighSlipAdvice: 'La eficiencia elegida deja una brecha amplia entre la velocidad geométrica y el avance. Revisa carga, caída de voltaje y temperatura.', diagnosisHeavyLoadAdvice: 'La masa da más peso a la corrección de carga. Trata la velocidad como un rango amplio y valida todo el conjunto.', diagnosisOverspeedAdvice: 'Las RPM sin carga son inusualmente altas. Comprueba los límites del motor, la batería y la hélice antes de aplicar potencia.', assumptionsLabel: 'Límite del modelo.', assumptionsText: 'La velocidad de paso es geométrica: paso x RPM cargadas. La eficiencia es un indicador introducido por el usuario para aproximar el deslizamiento; la masa aplica una corrección de carga pequeña y transparente. No se usan diámetro, curva de empuje ni viento.', safetyText: 'No es una garantía de vuelo. Mantén distancia de la hélice y valida corriente, temperatura, vibraciones y velocidad en una prueba controlada.', speedAxisStart: '0 km/h', speedAxisEnd: '300 km/h', noLoadCaption: 'sin carga', loadedCaption: 'cargado', slipCaption: 'deslizamiento', massUnit: 'g', speedUnit: 'km/h',
} satisfies Record<string, string>;
const faq = [
  { question: '¿Cómo se calcula la velocidad de paso de un dron FPV?', answer: 'Se multiplica el paso de la hélice por las revoluciones por minuto cargadas y se convierten las pulgadas por revolución a kilómetros por hora. Es una velocidad geométrica sin deslizamiento, no una promesa de velocidad aérea.' },
  { question: '¿Qué significa la eficiencia en esta estimación?', answer: 'La eficiencia es un indicador de planificación que representa la distancia entre la velocidad geométrica y el avance estimado. No sustituye una curva de rendimiento ni una prueba de vuelo.' },
  { question: '¿Por qué influye la masa de la aeronave?', answer: 'Una aeronave pesada suele cargar más el sistema, por lo que la herramienta aplica una corrección de RPM pequeña y limitada. Sin diámetro, empuje y par del motor, solo es una heurística transparente.' },
  { question: '¿Confirma esta calculadora que el dron es seguro?', answer: 'No. No valida motor, ESC, batería, hélice, estructura ni controlador. Comprueba los límites del fabricante y verifica el conjunto en un banco sujeto antes de volar.' },
  { question: '¿Por qué la velocidad real es menor que la de paso?', answer: 'La velocidad geométrica supone que la hélice avanza su paso nominal en cada vuelta. El deslizamiento, la forma de las palas, la caída de voltaje, la carga y las pérdidas de montaje reducen el avance útil.' },
];
const howTo = [
  { name: 'Introduce la propulsión', text: 'Escribe el KV del motor y el voltaje que esperas bajo carga, no solo el valor nominal de la batería.' },
  { name: 'Describe la hélice y el dron', text: 'Introduce el paso geométrico, una eficiencia prudente y la masa lista para volar. Usa un preset si necesitas un punto de partida.' },
  { name: 'Lee el trazado y valida', text: 'Compara la velocidad estimada con la de paso, el deslizamiento y la sensibilidad. Convierte el resultado en un plan de prueba y valida la propulsión con seguridad.' },
];
const seo: SEOSection[] = [
  { type: 'title', text: 'Estimar la velocidad de un dron FPV con el paso de hélice', level: 2 },
  { type: 'paragraph', html: 'Una estimación de velocidad para un dron FPV parte de la distancia que una hélice de paso fijo avanzaría en una vuelta. El KV y el voltaje proporcionan una primera aproximación de las RPM; la eficiencia y la masa ayudan a encuadrar una cifra de planificación. La calculadora mantiene visibles la velocidad geométrica y el avance estimado para que las hipótesis no se confundan con una medición.' },
  { type: 'title', text: 'Qué significa el trazado de velocidad', level: 2 },
  { type: 'table', headers: ['Señal', 'Interpretación'], rows: [['Velocidad de paso sin deslizamiento', 'Paso multiplicado por las RPM cargadas. Supone que la hélice avanza su paso nominal en cada vuelta.'], ['Velocidad de avance estimada', 'El valor sin deslizamiento multiplicado por la eficiencia introducida.'], ['Velocidad perdida por deslizamiento', 'Porcentaje de diferencia entre velocidad geométrica y avance estimado.'], ['Sensibilidad al paso', 'Resultado si el mismo montaje usara 0,5 pulgadas menos o más de paso.']] },
  { type: 'title', text: 'Cómo usar la estimación', level: 2 },
  { type: 'list', items: ['Usa el voltaje esperado bajo carga y no un valor optimista de batería recién cargada.', 'Parte de una combinación de motor y hélice conocida o de datos del fabricante.', 'Interpreta un deslizamiento alto como señal para revisar carga, caída de voltaje y elección de hélice.', 'Verifica corriente, temperatura, vibraciones y velocidad real en una prueba controlada antes de volar.'] },
  { type: 'title', text: 'Por qué el modelo tiene límites', level: 2 },
  { type: 'paragraph', html: 'El rendimiento de una hélice cambia con el avance, la geometría de las palas, la densidad del aire, la entrada de flujo y el ángulo de operación. Los modelos de hélices UAV de investigación usan datos medidos o identificados para cubrir esas condiciones. Esta calculadora es más estrecha: sirve para comparar hipótesis de montaje, pero no reemplaza una tabla de hélice, un banco de empuje ni instrumentación de vuelo.' },
  { type: 'tip', title: 'Usa la brecha para decidir', html: 'Si un montaje parece rápido solo porque su cifra sin deslizamiento es alta, revisa la distancia hasta la estimación ajustada por eficiencia. Una hélice de menor paso puede cambiar velocidad máxima por una carga más manejable, pero también necesita una comprobación real.' },
];
const schemas: FpvDroneSpeedLocaleContent['schemas'] = [
  { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) } as WithContext<FAQPage>,
  { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) } as WithContext<HowTo>,
  { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' } } as WithContext<SoftwareApplication>,
];
export const content: FpvDroneSpeedLocaleContent = { slug, title, description, ui, seo, faq, bibliography: BIBLIOGRAPHY_ITEMS, howTo, schemas };
